# # # # # # # #
#  M i n h o  #
# # # # # # # #

# Basic
name:               "Jeon lab"
title:              "as called as Cognitive Neuroscience Lab"
description:        "this is a page for Jeon lab, we are cognitive neurosciece and neuroimaging lab based in DGIST"


# URL
url:                https://cogneurojeon.github.io/
baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publication"
  - name:           "people"
    href:           "/people"
  - name:           "news & updates"
    href:           "/news"
  - name:           "gallery"
    href:           "/gallery"
  - name:           "jobs"
    href:           "/jobs"
  - name:           "contact us"
    href:           "/contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
